version: "3"
services:
  es:
    image: elasticsearch:7.17.6
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  web:
    image: asprin/foodtrucks-web:2.0.0
    #command: python3 app.py
    depends_on:
      - es
    ports:
      - 80:5000
    volumes:
      - ./flask-app:/opt/flask-app
volumes:
    esdata1:
      driver: local
